# Nixpacks configuration file

[phases]
  install = '''
  cd Server && npm install
  cd ../Front && npm install
  '''
  build = '''
  cd Front && npm run build
  '''

[start]
  cmd = "cd Server && npm start"

[pkgs]
  # Specify Node.js and npm as required packages
  pkgs = ["nodejs", "npm"]