# Nixpacks configuration

[phases]

# Backend (Node.js server)
[phases.backend]
  cmds = [
    "cd Server && npm install"
  ]

# Frontend (React app)
[phases.frontend]
  dependsOn = ["backend"]
  cmds = [
    "cd Front && npm install && npm run build"
  ]

# Start both backend and frontend
[start]
  cmds = [
    "pm2 start Server --name 'Server' -- run start",
    "cd Front && pm2 start npm --name 'React' -- run start"
  ]