# Nixpacks configuration file

[phases.install]
# Install Node.js and npm
pkgs = ["nodejs", "npm"]
commands = [
  "cd Server && npm install",
  "cd ../Front && npm install"
]

[phases.build]
# Build the frontend (React app in Front directory)
commands = [
  "cd Front && npm run build"
]

[start]
# Start the backend (Server)
cmd = "cd Server && npm start"
