# nixpacks.toml
[variables]
    NPM_CONFIG_UPDATE_NOTIFIER = 'false'
    NPM_CONFIG_FUND = 'false'

# Download Caddy from Nix
[phases.caddy]
    dependsOn = ['setup']
    nixpkgsArchive = 'ba913eda2df8eb72147259189d55932012df6301' # Caddy v2.8.4
    nixPkgs = ['caddy']

# Format the Caddyfile
[phases.fmt]
    dependsOn = ['caddy']
    cmds = ['caddy fmt --overwrite Caddyfile']

# Start the Caddy web server
[start]
    cmd = 'exec caddy run --config Caddyfile --adapter caddyfile 2>&1'