# Nixpacks configuration file

[phases.install]
commands = [
  "cd Server && npm install",
  "cd ../Front && npm install"
]

[phases.build]
commands = [
  "cd Front && npm run build"
]

[start]
cmd = "cd Server && npm start"

[pkgs]
pkgs = ["nodejs", "npm"]
