name: Deploy to Railway

on:
  push:
    branches: [main]  # Change to your branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js version (you can use 14.x, 16.x, etc. depending on your project)
      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      # Install dependencies for both backend and frontend
      - name: Install packages
        run: |
          cd Server && npm install   # Install for Node.js backend
          cd ../Front && npm install  # Install for React frontend

      # Build the React frontend
      - name: Build React App
        run: |
          cd Front
          CI=false npm run build

      # Install the Railway CLI globally
      - name: Install Railway
        run: npm install -g @railway/cli

      # Deploy to Railway using the Railway CLI
      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}