name: Deploy to Railway

on:
  push:
    branches: [main]  # Trigger on main branch or another branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      # Install and build backend (Node.js)
      - name: Install Backend Dependencies
        run: |
          cd Server
          npm install

      - name: Deploy Backend to Railway
        run: railway up --service backend-service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      # Install and build frontend (React)
      - name: Install Frontend Dependencies
        run: |
          cd Front
          npm install
          npm run build

      - name: Deploy Frontend to Railway
        run: railway up --service frontend-service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
